### PR TITLE
Improve Get-VMInformation.ps1

### PR DESCRIPTION
**Pull request by JonZeolla**
This should greatly improve the performance of `Get-VMInformation.ps1` (my testing showed a ~3.5x speed increase), make it more portable (does not require `rsc`/`rsc.exe` and can run anywhere PowerShell >= 3.0 will), and cleans up the credential handling to make it more secure.

### CODE REVIEW

**Comment by JonZeolla** [comment]
So I tried this script out on Windows today and it has a small issue that I'm going to attempt to fix by using `System.Net.Http.HttpClient` anywhere that I need to do a GET against an API endpoint and also provide a body.

In my script I attempt to gather information about an account using [this endpoint](http://reference.rightscale.com/api1.5/resources/ResourceAccounts.html) via:
```
Invoke-RestMethod -Uri https://$endpoint/api/accounts/$account -Headers $headers -Method GET -WebSession $webSessions["$account"] -Body "email=$($rscreds.UserName)&password=$($rscreds.GetNetworkCredential().Password)&account_href=/api/accounts/$account"
```

It appears that your API requires that credentials for this call be sent in the body of the GET request in order to be authorized, and, although that is RFC-compliant, [.NET does not support it](https://github.com/dotnet/corefx/issues/11211) as a part of `Invoke-RestMethod`.  I am not familiar with `System.Net.Http.HttpClient` but I'm going to see if I can move to it instead.  I do not get this issue on my macOS system.

**Comment by srpomeroy** [comment]
@JonZeolla You should be able to use a web session cookie as an alternative. Auth once, and use the web session for the subsequent calls.
Auth: https://github.com/rs-services/cos_assets/blob/master/RightLink_Utilization/Get-OrgUtilizationData.ps1#L52-L63
Use web session: https://github.com/rs-services/cos_assets/blob/master/RightLink_Utilization/Get-OrgUtilizationData.ps1#L97

RS API Example Docs: http://docs.rightscale.com/api/api_1.5_examples/authentication.html#powershell-example-call

**Comment by JonZeolla** [comment]
That last commit should fix it up, I was already using a web session cookie but it appears that when I last attempted this without a `-Body` on the `GET` requests, I was adding `account_href` as a filter to  my calls against [`instances`](http://reference.rightscale.com/api1.5/resources/ResourceInstances.html#index_filters) which was failing because you can't do that.  I need to test this on Windows still, but it worked fine on my macOS box.

**Comment by JonZeolla** [comment]
@srpomeroy is there a better way to approach [this](https://github.com/rs-services/cos_assets/blob/91966cd7eadd3da0b39d7616b801a7022c8582dd/RightLink_Utilization/Get-VMInformation.ps1#L118) other than asking for the endpoint for each account specified, or just trying all of the possible endpoints?  I looked for it in the documentation but wasn't able to find a single smart URL endpoint so we don't need the us-3, us-4 stuff.  In my script if someone provides a parent account it will automatically pull the right endpoints for the children.

**Comment by JonZeolla** [comment]
Okay, tested this on Windows and macOS, both are working just fine.  Ready for review.

**Comment by srpomeroy** [comment]
@rshade merged in #14

**Pull request merged**
